apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j5tv5wbxf-python
  janus-idp.io/tekton: j5tv5wbxf-python
  backstage.io/kubernetes-id: j5tv5wbxf-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5tv5wbxf-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
