apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: j5tv5wbxf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j5tv5wbxf-python 
  name: j5tv5wbxf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: j5tv5wbxf-python 
